# Configure appearance (require noctalia)

set -g status-style "bg=#{@noctalia_surface_container_low},fg=#{@noctalia_on_surface}"
set -g status-left-length 20
set -g status-right-length 50
set -g status-left '#[fg=#{@noctalia_primary},bold] #S #[fg=#{@noctalia_outline_variant}]│ '
set -g status-right '#[fg=#{@noctalia_outline_variant}]│ #[fg=#{@noctalia_on_surface}]%H:%M #[fg=#{@noctalia_outline_variant}]│ #[fg=#{@noctalia_on_surface_variant}]%d-%b-%y '
setw -g window-status-format ' #[fg=#{@noctalia_on_surface_variant}]#I:#W '
setw -g window-status-current-format '#[fg=#{@noctalia_primary},bold] #I:#W '
setw -g window-status-activity-style "bg=#{@noctalia_tertiary_container},fg=#{@noctalia_on_tertiary_container}"
setw -g window-status-bell-style "bg=#{@noctalia_error_container},fg=#{@noctalia_on_error_container},bold"
set -g pane-border-style "fg=#{@noctalia_outline_variant}"
set -g pane-active-border-style "fg=#{@noctalia_primary}"
