-- Generated by nwg-displays on 2026-06-19 at 11:47:21. Do not edit manually.

hl.monitor({
    output = "desc:Chimei Innolux Corporation 0x14D5",
    mode = "1920x1080@60.01",
    position = "1920x0",
    scale = 1.0
})
hl.monitor({
    output = "desc:Samsung Electric Company C27F390 H4ZM604586",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 1.0
})
